blank_issues_enabled: false
contact_links:
  - name: "About the DOAPR 📃"
    url: "https://doapr.coar-repositories.org"
    about: "Questions regarding the Directory of Open Access Pre-print Repositories?"