blank_issues_enabled: false
contact_links:
  - name: About the DOAPR 📃
    url: https://example.org/about/
    about: Questions regarding the Directory of Open Access Pre-print Repositories? Take a look at our FAQs
