languageCode: "en-gb"
uglyURLs: false
title: "Directory of Open Access Preprint Repositories"
theme: "doapr"
enableRobotsTXT: true
disableKinds: [ "RSS" ]
metaDataFormat: "yaml"
enableGitInfo: false
disablePathToLower: true
params:
  feedback_new_repo_url: "https://github.com/antleaf/doapr/issues/new?assignees=&labels=&template=a-add-a-preprint-repository-to-the-doapr.md&title=%5BNew+Entry%5D"
  feedback_update_repo_url_prefix: "https://github.com/antleaf/doapr/issues/new?assignees=&labels=&template=b-update-a-preprint-repository.md"
  feedback_bug_report_url: "https://github.com/antleaf/doapr/issues/new?assignees=&labels=bug&template=d-bug_report.md&title=%5BBug+Report%5D"
  enableAnalytics: false  # this param may be overridden in production/development envs
taxonomies:
  tag: "tags"
outputs:
  page: [ html,json ]
menu:
  navbar:
    - identifier: repositories-dropdown
      name: Repositories
      weight: 2
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
