languageCode: "en-gb"
uglyURLs: false
title: "Directory of Open Access Preprint Repositories"
theme: "doapr"
enableRobotsTXT: true
disableKinds: [ "RSS" ]
metaDataFormat: "yaml"
enableGitInfo: false
disablePathToLower: true
params:
  feedback_new_repo_url: "https://github.com/antleaf/doapr/issues/new?assignees=&labels=&template=a-add-a-preprint-repository-to-the-doapr.md&title=%5BNew+Entry%5D"
  feedback_update_repo_url_prefix: "https://github.com/antleaf/doapr/issues/new?assignees=&labels=&template=b-update-a-preprint-repository.md"
  feedback_bug_report_url: "https://github.com/antleaf/doapr/issues/new?assignees=&labels=bug&template=d-bug_report.md&title=%5BBug+Report%5D"
taxonomies:
  tag: "tags"
outputs:
  page: [ html,json ]
menu:
  navbar:
    - identifier: home
      name: Home
      weight: 1
      url: "/"
    - identifier: repositories-dropdown
      name: Repositories
      weight: 2
    - identifier: repositories-general
      weight: 2.0
      name: "1. General"
      url: "/repositories"
      parent: repositories-dropdown
    - identifier: repositories-by-function
      weight: 2.2
      name: "2. Function"
      url: "/repositories-by-function/"
      parent: repositories-dropdown
    - identifier: repositories-by-open-science
      weight: 2.3
      name: "3. Support for Open Science"
      parent: repositories-dropdown
      url: "/repositories-by-open-science"
    - identifier: functions
      weight: 4
      name: "Functions"
      url: "/functions"
    - identifier: disciplines
      weight: 5
      name: "Disciplines"
      url: "/disciplines"
    - identifier: services
      name: "Integrated Services"
      url: "/services"
      weight: 6
    - identifier: feedback
      name: "Feedback"
      url: "/feedback"
      weight: 9
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
