languageCode: "en-gb"
uglyURLs: false
title: "DOAPR"
theme: "doapr"
enableRobotsTXT: true
disableKinds: [ "RSS" ]
metaDataFormat: "yaml"
enableGitInfo: false
disablePathToLower: true
params:
taxonomies:
  tag: "tags"
outputs:
  page: [ html,json ]
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: pygments
    tabWidth: 4
